repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      # run ruff linting on all files
      - id: ruff
        files: .*

      # run ruff formatting on all files
      - id: ruff-format
        files: .*
